# Postprovision hook: writes the app .env from azd provisioning outputs.
# azd exposes Bicep outputs as environment variables to this hook.
# AGENT_NAME and the Content Understanding API version are static (the agent
# is created manually in the Foundry portal for Module 2c).

$ErrorActionPreference = 'Stop'
$envPath = Join-Path (Split-Path $PSScriptRoot -Parent) '.env'

$lines = @(
    '# Generated by `azd up` (scripts/write-dotenv.ps1). Do not commit.'
    "FOUNDRY_PROJECT_ENDPOINT=$env:FOUNDRY_PROJECT_ENDPOINT"
    "CHAT_DEPLOYMENT=$env:CHAT_DEPLOYMENT"
    "MULTIMODAL_DEPLOYMENT=$env:MULTIMODAL_DEPLOYMENT"
    "IMAGE_DEPLOYMENT=$env:IMAGE_DEPLOYMENT"
    "EMBEDDING_DEPLOYMENT=$env:EMBEDDING_DEPLOYMENT"
    'AGENT_NAME=wealth-concierge'
    "SPEECH_REGION=$env:SPEECH_REGION"
    "SPEECH_RESOURCE_ID=$env:SPEECH_RESOURCE_ID"
    "CONTENT_UNDERSTANDING_ENDPOINT=$env:CONTENT_UNDERSTANDING_ENDPOINT"
    'CONTENT_UNDERSTANDING_API_VERSION=2025-11-01'
    "LANGUAGE_ENDPOINT=$env:LANGUAGE_ENDPOINT"
    ''
    '# OPTIONAL Module 4 demos (Parts B & C). VOICE_LIVE_MODEL is provisioned;'
    '# SPEECH_MCP_URL is a preview Foundry Tools endpoint you set manually.'
    "VOICE_LIVE_MODEL=$env:VOICE_LIVE_MODEL"
    'VOICE_LIVE_ENDPOINT='
    'SPEECH_MCP_URL='
)

Set-Content -Path $envPath -Value $lines -Encoding utf8
Write-Host "Wrote $envPath"
